// Mocks generated by Mockito 5.4.2 from annotations
// in workout_app/test/mock/composed_workout_dao.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:workout_app/database/dao/composed_workout_dao.dart' as _i4;
import 'package:workout_app/database/dao/dao_result.dart' as _i3;
import 'package:workout_app/database/model/embedded_object/workout_with_exercises_and_sets_entity.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDaoResult_1<T> extends _i1.SmartFake implements _i3.DaoResult<T> {
  _FakeDaoResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ComposedWorkoutDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockComposedWorkoutDao extends _i1.Mock
    implements _i4.ComposedWorkoutDao {
  MockComposedWorkoutDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.Database);

  @override
  set database(_i2.Database? _database) => super.noSuchMethod(
        Invocation.setter(
          #database,
          _database,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.DaoResult<List<_i6.WorkoutWithExercisesAndSetsEntity>>>
      findAll() => (super.noSuchMethod(
            Invocation.method(
              #findAll,
              [],
            ),
            returnValue: _i5.Future<
                    _i3.DaoResult<
                        List<_i6.WorkoutWithExercisesAndSetsEntity>>>.value(
                _FakeDaoResult_1<List<_i6.WorkoutWithExercisesAndSetsEntity>>(
              this,
              Invocation.method(
                #findAll,
                [],
              ),
            )),
          ) as _i5.Future<
              _i3.DaoResult<List<_i6.WorkoutWithExercisesAndSetsEntity>>>);

  @override
  _i5.Future<
      _i3.DaoResult<List<_i6.WorkoutWithExercisesAndSetsEntity>>> findByFilter(
          _i4.ComposedWorkoutFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByFilter,
          [filter],
        ),
        returnValue: _i5.Future<
                _i3
                .DaoResult<List<_i6.WorkoutWithExercisesAndSetsEntity>>>.value(
            _FakeDaoResult_1<List<_i6.WorkoutWithExercisesAndSetsEntity>>(
          this,
          Invocation.method(
            #findByFilter,
            [filter],
          ),
        )),
      ) as _i5
          .Future<_i3.DaoResult<List<_i6.WorkoutWithExercisesAndSetsEntity>>>);

  @override
  _i5.Future<_i3.DaoResult<int>> add(
          _i6.WorkoutWithExercisesAndSetsEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [entity],
        ),
        returnValue: _i5.Future<_i3.DaoResult<int>>.value(_FakeDaoResult_1<int>(
          this,
          Invocation.method(
            #add,
            [entity],
          ),
        )),
      ) as _i5.Future<_i3.DaoResult<int>>);

  @override
  _i5.Future<_i3.DaoResult<bool>> update(
          _i6.WorkoutWithExercisesAndSetsEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue:
            _i5.Future<_i3.DaoResult<bool>>.value(_FakeDaoResult_1<bool>(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i5.Future<_i3.DaoResult<bool>>);

  @override
  _i5.Future<_i3.DaoResult<bool>> delete(_i4.ComposedWorkoutFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [filter],
        ),
        returnValue:
            _i5.Future<_i3.DaoResult<bool>>.value(_FakeDaoResult_1<bool>(
          this,
          Invocation.method(
            #delete,
            [filter],
          ),
        )),
      ) as _i5.Future<_i3.DaoResult<bool>>);

  @override
  _i5.Future<void> init(_i5.Future<_i2.Database>? database) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [database],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
