// Mocks generated by Mockito 5.4.2 from annotations
// in workout_app/test/mock/database_observer.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_app/repository/database_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DatabaseObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseObserver extends _i1.Mock implements _i2.DatabaseObserver {
  MockDatabaseObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> didDatabaseBackupRestored() => (super.noSuchMethod(
        Invocation.method(
          #didDatabaseBackupRestored,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
