// Mocks generated by Mockito 5.4.2 from annotations
// in workout_app/test/mock/drive_api_factory.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:googleapis/drive/v3.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_app/port/google_drive_port.dart' as _i2;
import 'package:workout_app/port/google_sign_in_port.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DriveApiFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveApiFactory extends _i1.Mock implements _i2.DriveApiFactory {
  MockDriveApiFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DriveApi?> create(_i5.GoogleSignInPort? signInPort) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [signInPort],
        ),
        returnValue: _i3.Future<_i4.DriveApi?>.value(),
      ) as _i3.Future<_i4.DriveApi?>);
}
