// Mocks generated by Mockito 5.4.2 from annotations
// in workout_app/test/mock/google_sign_in_port.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_app/port/google_sign_in_port.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GoogleSignInPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInPort extends _i1.Mock implements _i2.GoogleSignInPort {
  MockGoogleSignInPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Client?> get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _i3.Future<_i4.Client?>.value(),
      ) as _i3.Future<_i4.Client?>);

  @override
  _i3.Future<bool> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
