// Mocks generated by Mockito 5.4.2 from annotations
// in workout_app/test/mock/media.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:_discoveryapis_commons/src/requests.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Media].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedia extends _i1.Mock implements _i2.Media {
  MockMedia() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<int>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<List<int>>.empty(),
      ) as _i3.Stream<List<int>>);

  @override
  String get contentType => (super.noSuchMethod(
        Invocation.getter(#contentType),
        returnValue: '',
      ) as String);
}
